from parsers.bitsadmin import interface
from parsers.browserhistory import interface
from parsers.csvparser import interface
from parsers.jumplist import interface
from parsers.mft import interface
from parsers.prefetch import interface
from parsers.pshistory import interface
from parsers.recyclebin import interface
from parsers.regsk import interface
from parsers.rua import interface
from parsers.sccm import interface
from parsers.scheduledtasks import interface
from parsers.srum import interface
from parsers.usnjrnl import interface
from parsers.wer import interface
from parsers.winevents import interface
from parsers.wmipersistence import interface